# Generated by Django 4.2 on 2023-04-10 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeelsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feel_num', models.IntegerField(verbose_name='самочувствие')),
                ('feel_info', models.TextField(blank=True, verbose_name='самочувствие подробно')),
                ('location', models.CharField(max_length=250, verbose_name='город')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('temp_c', models.IntegerField(verbose_name='temp_c')),
                ('temp_c_feel', models.IntegerField(verbose_name='temp_c_feel')),
                ('hum', models.IntegerField(verbose_name='hum')),
                ('wind', models.IntegerField(verbose_name='wind')),
                ('wind_gust', models.IntegerField(verbose_name='wind_gust')),
                ('pressure_mm', models.IntegerField(verbose_name='pressure_mm')),
                ('k_index', models.IntegerField(verbose_name='k_index')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
