# Generated by Django 4.2 on 2023-04-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feel_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feelsdata',
            name='feel_num',
            field=models.FloatField(verbose_name='самочувствие'),
        ),
        migrations.AlterField(
            model_name='feelsdata',
            name='hum',
            field=models.FloatField(verbose_name='hum'),
        ),
        migrations.AlterField(
            model_name='feelsdata',
            name='k_index',
            field=models.FloatField(verbose_name='k_index'),
        ),
        migrations.AlterField(
            model_name='feelsdata',
            name='pressure_mm',
            field=models.FloatField(verbose_name='pressure_mm'),
        ),
        migrations.AlterField(
            model_name='feelsdata',
            name='temp_c',
            field=models.FloatField(verbose_name='temp_c'),
        ),
        migrations.AlterField(
            model_name='feelsdata',
            name='temp_c_feel',
            field=models.FloatField(verbose_name='temp_c_feel'),
        ),
        migrations.AlterField(
            model_name='feelsdata',
            name='wind',
            field=models.FloatField(verbose_name='wind'),
        ),
        migrations.AlterField(
            model_name='feelsdata',
            name='wind_gust',
            field=models.FloatField(verbose_name='wind_gust'),
        ),
    ]
