# Generated by Django 4.2 on 2023-04-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_requests', '0002_alter_allrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allrequest',
            name='user',
        ),
    ]
